name: Install and Cache Dependencies
description: Install and cache dependencies
inputs:
  caching:
    description: Enable caching (default = true)
    required: false
    default: "true"
outputs:
  cache-hit:
    description: Cache hit
    value: ${{ steps.set-cache-hit.outputs.cache-hit }}
runs:
  using: composite
  steps:
    - name: Install Bun
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: 1.2.8

    - name: Cache dependencies
      id: cache-deps
      if: ${{ fromJSON(inputs.caching) == true }}
      uses: actions/cache@v4
      with:
        path: |
          ~/.bun/install/cache
        key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lock') }}

    - name: Install Dependencies
      shell: bash # when use `run:` you need to specify shell
      run: bun i

    - name: set output cache-hit
      id: set-cache-hit
      shell: bash
      run: echo "cache-hit=${{ steps.cache-deps.outputs.cache-hit }}" >> $GITHUB_OUTPUT
