name: Web deployment
on:
  workflow_call:
    inputs:
      artifact-name:
        type: string
        required: false
        default: dist
    secrets:
      some-secret:
        required: true
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: download dist folder
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.artifact-name }}

      - name: List all files
        run: ls -R
