name: Echo Vars and Secrets
on:
  workflow_dispatch:
jobs:
  echo-dev:
    environment: "Development"
    runs-on: ubuntu-latest
    env:
      API_URL: ${{ vars.API_URL }}
      POSTGRES_URL: ${{ secrets.POSTGRES_URL }}

    steps:
      - name: Echo Variables
        run: echo "API_URL:\ $API_URL"
      - name: Echo Secrets
        run: echo "POSTGRES_URL:\ $POSTGRES_URL"

  echo-prod:
    environment: "Production"
    runs-on: ubuntu-latest
    env:
      API_URL: ${{ vars.API_URL }}
      POSTGRES_URL: ${{ secrets.POSTGRES_URL }}

    steps:
      - name: Echo Variables
        run: echo "API_URL:\ $API_URL"
      - name: Echo Secrets
        run: echo "POSTGRES_URL:\ $POSTGRES_URL"
